# Generated by Django 5.0 on 2024-01-07 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantre', models.CharField(max_length=99)),
                ('estrellas', models.FloatField(max_length=250)),
                ('ubicacion', models.CharField(max_length=99)),
                ('fecha_de_visita', models.DateField()),
                ('fecha_de_reseña', models.DateField(verbose_name=datetime.datetime(2024, 1, 7, 18, 9, 10, 766408))),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=99)),
                ('descripcion', models.CharField(max_length=250)),
                ('ubicacion', models.CharField(max_length=99)),
                ('instagram', models.URLField()),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=99)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('reseñas', models.CharField(max_length=99)),
            ],
        ),
    ]
