# Generated by Django 5.0 on 2024-01-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppResto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseña',
            name='estrellas',
        ),
        migrations.AlterField(
            model_name='reseña',
            name='fecha_de_reseña',
            field=models.DateField(),
        ),
    ]
