# Generated by Django 5.0 on 2024-01-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppResto', '0002_remove_reseña_estrellas_alter_reseña_fecha_de_reseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseña',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='foto',
        ),
        migrations.AddField(
            model_name='reseña',
            name='estrellas',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurante',
            name='reseñas',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
