# Generated by Django 5.0.1 on 2024-01-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppResto', '0003_remove_reseña_foto_remove_restaurante_foto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseña',
            old_name='restaurantre',
            new_name='restaurante',
        ),
    ]
