# Generated by Django 5.0.1 on 2024-01-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppResto', '0004_rename_restaurantre_reseña_restaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='reseña',
            field=models.CharField(default='cargado antes de modificacion', max_length=150),
            preserve_default=False,
        ),
    ]
