# Generated by Django 5.0.1 on 2024-01-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppResto', '0005_reseña_reseña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseña',
            old_name='estrellas',
            new_name='puntuacion',
        ),
    ]
