# Generated by Django 5.0.1 on 2024-01-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppResto', '0006_rename_estrellas_reseña_puntuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='foto',
            field=models.ImageField(default='null', upload_to=''),
            preserve_default=False,
        ),
    ]
