# Generated by Django 5.0 on 2024-01-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppResto', '0009_reseña_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='reseñas',
            new_name='calificacion',
        ),
    ]
