# Generated by Django 5.0.1 on 2024-01-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppResto', '0010_rename_reseñas_restaurante_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='reseñas',
        ),
        migrations.AddField(
            model_name='reseña',
            name='usuario',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
