# Generated by Django 5.0.1 on 2024-01-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppResto', '0011_remove_usuario_reseñas_reseña_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='usuario',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
