# Generated by Django 5.0.1 on 2024-01-15 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppResto', '0012_restaurante_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='fecha_de_reseña',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppResto.restaurante'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='calificacion',
            field=models.FloatField(default=0.0),
        ),
    ]
