# Generated by Django 5.0.1 on 2024-01-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppResto', '0014_user_delete_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password1',
        ),
    ]
