# Generated by Django 5.0.1 on 2024-01-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppResto', '0015_rename_password_user_password1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseña',
            name='ubicacion',
        ),
    ]
